### ISSUE TITLE
Where should enableKeyboardLock and reservedKeyCodes be stored?

### ISSUE THREAD

**Issue by domenic** [garykac/system-keyboard-lock#1]
One big issue to figure it is where the enableKeyboardLock and reservedKeyCodes are meant to be stored. They're certainly not stored in "the user agent", as that would mean that they are the same across all web sites. I see a few choices:

- The browsing context (~ a "tab" in your browser). This seems unlikely, as it would mean they persist across navigation within that browsing context (even to cross-origin sites).
- Every Window/environment settings object (they are 1:1). This would mean that if you inject code into about:blank and then navigate, the keyboard lock would be preserved (the Window is reused so all its values remain). But if you do document.open(), the keyboard lock would be lost (the Window is re-created).
- Every Document that has a browsing context. (The latter clause is important so that document.implement.createDocument() or XHR responseDocument do not get this ability.) This would mean that navigating from about:blank to a new document loses keyboard lock, but doing document.open() does not.

So probably either Window or Document. I don't see a real reason to prefer one over the other; maybe Document is most conventional.

Once you've figured that out, it's important to say how to get to that variable inside your algorithms. So, let's say it was Window. Then step 1 of requestSystemKeyboardLock would be:

1. Reset this Navigator object's relevant global object's reservedKeyCodes to be an empty sequence.

If it was the Document, it would be

1. Reset this Navigator object's relevant global object's associated Document's reservedKeyCodes to be an empty sequence.

Similarly for references to enableKeyboardLock and so on.

**Comment by domenic** [comment]
I guess you could also store on the Navigator. Since it is 1:1 with Window, it would have the same observable consequences, but would allow writing slightly simpler spec text as you could omit "relevant global object's"

**Comment by garykac** [comment]
Thanks for describing the implications of each location - I was unaware of a bunch of that.

I've put it in navigator.

Is it possible to (and does it make sense to) include these objects in the Navigator partial interface IDL as a private?  I haven't seen that done elsewhere (nor have I seen "private" in IDL), so I'm guessing the answer is no. But there's a part of me that thinks it would make sense to do so.

**Comment by domenic** [comment]
Yeah, we don't yet have any formal way of denoting such "internal slots". It's definitely something we'd like to do. https://github.com/whatwg/infra/issues/40 was opened recently to track that, but my guess is we'll end up doing it in Web IDL.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#1
