### ISSUE TITLE
requestFullScreen is on Document but requestSystemKeyboardLock is on Navigator

### ISSUE THREAD

**Issue by dtapuska** [garykac/system-keyboard-lock#12]
This seems a little odd given what is currently on the Navigator object (there aren't any functions and most of values are only readonly). Not sure what the motivation to add it to the Navigator object is.

@foolip Do you have any opinion?

**Comment by jamiewalch** [comment]
We originally had it on Document but someone (I forget who) suggested moving it to Navigator. I don't have a preference either way.

**Comment by Hzj-jie** [comment]
I believe requestFullScreen() is on Element, i.e. the UA should be able to fullscreen a certain Element instead of entire page.
But keyboard lock is Element independent, we allow the page to receive the events instead of a certain Element.

**Comment by foolip** [comment]
Window, Document and Navigator are all more less "one per frame" objects, and AFAICT there's no rhyme or reason to where new APIs are added. I would personally default to putting things on Window, or [WindowOrWorkerGlobalScope](https://html.spec.whatwg.org/#windoworworkerglobalscope-mixin) if it also makes sense in workers.

But there's no chance for consistency, so ¯\_(ツ)_/¯

@domenic?

**Comment by domenic** [comment]
Not Document, that's special due to document.open(), document.implementation.createDocument(), etc.

Between Navigator and Window often people go for Navigator to avoid polluting the global namespace, I believe. That seems reasonable but so does putting things on Window. *Shrug*.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#12
