### ISSUE TITLE
Spec seems to describe an implementation

### ISSUE THREAD

**Issue by dtapuska** [garykac/system-keyboard-lock#13]
When reading:
https://garykac.github.io/system-keyboard-lock/#key-press-handler

It seems that the "system key press handler" is describing an implementation. An alternate implementation is that you could just have a table and know that the registered document/navigator has priority over executing the UA default action for these events.

It isn't clear to me that you need to hook the system listeners in order to implement this.

**Comment by jamiewalch** [comment]
The system hook is needed for keyboard shortcuts that the browser would not otherwise receive; Alt+Tab is the canonical example we've been using for that. Other keys could be handled either by the same hook or by the regular input processing pipeline, at the discretion of the UA.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#13
