### ISSUE TITLE
Web page may receive out of order key events

### ISSUE THREAD

**Issue by Hzj-jie** [garykac/system-keyboard-lock#15]
@dtapuska mentioned this good question.
Once a web page requests some keys, according to #9, these keys should not be processed by browser. The behavior may introduce the out of order key events. E.g.
- Web page requests "W" key.
- User types "Q" and "W" in sequence.
- "Q" is consumed or delayed by browser processing logic, maybe IME.
- Web page receives "W" then "Q", or "W" only.

I do not think this could be a big deal. If the web page needs both "Q" and "W", it should request both keys. Otherwise, relying on "Q" is not a reasonable behavior. But we may explicitly call out this issue in the spec.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#15
