### ISSUE TITLE
Define a DOMException for errors

### ISSUE THREAD

**Issue by Hzj-jie** [garykac/system-keyboard-lock#19]
This should cover the #18, as well as the implementation specific limitations. A must-have is a field to indicate whether the error could recover after a retry, or the request is rejected by user agents because of a permission request.

**Comment by Hzj-jie** [comment]
After discussed with @jamiewalch, we believe the field to indicate whether the error could be recovered after a retry is not necessary. Something like
```
User agent should only reject and discard the request in following situations:
1. the request is not allowed by the user. (Permission)
2. there is already a pending request.
```
should be sufficient.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#19
