### ISSUE TITLE
low-level keyboard event handler

### ISSUE THREAD

**Issue by domenic** [garykac/system-keyboard-lock#2]
This term should probably be defined somewhere separate from the algorithm that registers it. Then it can get the proper treatment it deserves in terms of what normative effects it has, the interesting notes nearby, and so on.

It should explain what normative effect it has in as much detail as possible, although understandably this is kind of difficult. Currently it says "process keyboard events". Maybe expand on this a bit, i.e. something like "ensure that KeyboardEvent events are fired instead of performing the usual action of the system keyboard shortcut".

Also, it would be best to not use "event handler" since that has a specific meaning. Maybe "keyboard trap" or similar would be better.

Also, consistently use low-level or low level. I think with a hyphen is a bit better?

**Comment by domenic** [comment]
Oh, I see, the normative effects are largely explained in section 3. Quite nice. I think the bullet points should move there, and low-level keyboard event handler (or its rename) shoud link to a definition contained there.

**Comment by garykac** [comment]
Fixed in 5d8c3e7bc4ce2a95f94e735e7b6b92b407251d3a

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#2
