### ISSUE TITLE
cancelSystemKeyboardLock() should be automatically called when document is unloading

### ISSUE THREAD

**Issue by Hzj-jie** [garykac/system-keyboard-lock#22]
If the web page has not actively called cancelSystemKeyboardLock(), whenever the unloading document cleanup steps run with a document, cancelSystemKeyboardLock() is implicitly called. i.e. The keyboard lock API is session-based, and won't be kept by the user agents.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#22
