### ISSUE TITLE
Is the concept "KeyboardEvent code" defined anywhere?

### ISSUE THREAD

**Issue by domenic** [garykac/system-keyboard-lock#4]
Right now it links to an IDL member, but ideally there should be a definition like "a KeyboardEvent code is one of the following strings" in some spec.

**Comment by garykac** [comment]
They're all defined in the UIevents-code :https://w3c.github.io/uievents-code/

(but it sounds like we need to make sure the link to that spec is more prominent)

**Comment by domenic** [comment]
I guess it's just an editorial thing where that spec never defines the term "code values" to mean "the list of all things in the first column of the various tables inside https://w3c.github.io/uievents-code/#code-value-tables"

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#4
