### ISSUE TITLE
"System" keyword in the Navigator API is not that proper

### ISSUE THREAD

**Issue by Hzj-jie** [garykac/system-keyboard-lock#6]
Considering the API is for all keys instead of OS reserved key combinations, I would suggest to change,
`Navigator.requestSystemKeyboardLock()`
into
`Navigator.requestKeyLock()`

And similar as
`Navigator.cancelSystemKeyboardLock()`.

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#6
