### ISSUE TITLE
Navigator.requestSystemKeyboardLock() may return Promise<void> instead of void

### ISSUE THREAD

**Issue by Hzj-jie** [garykac/system-keyboard-lock#7]
Considering this is an extremely powerful API, which allows webpage to intercept any keys. Some browser vendors may implement a user notification or prompt to decide whether these APIs should be allowed or now. Meanwhile, web page may need a signal to indicate when the reserved keys are available, or whether the user declined the request. So it may fall back to use alternative keys.
So I suggest to change
`void Navigator.requestSystemKeyboardLock()`
into
`Promise<void> Navigator.requestSystemKeyboardLock()`

Once the Promise resolves, the web page should be able to retrieve the keys it requested.
The Promise will reject only if the user actively disallowed the API.
Due to the "best effort" principle of these APIs, no matter whether the keys or key combinations can be successfully retrieved, e.g. ctrl+alt+del is never cancelable on Windows, the Promise always resolves, once users or browser allowed the API.

`void Navigator.cancelSystemKeyboardLock()`
is not impacted by this change.

**Comment by mgiuca** [comment]
+1

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#7
